[env]
WINIT_X11_SCALE_FACTOR = "1.0"

[window]
dynamic_padding = true
decorations = "None"
opacity = 0.8

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { style = "Bold" }
italic = { style = "Italic" }
bold_italic = { style = "Bold Italic" }
