[icons]
icons = "awesome5"

[theme]
theme = "gruvbox-dark"
[theme.overrides]
separator=""

[[block]]
block = "disk_space"
# format = " $icon $available "
warning = 5
interval = 30
[block.theme_overrides]
idle_bg = "#076678"

[[block]]
block = "memory"
format = " $icon$mem_used($mem_used_percents) "
[block.theme_overrides]
idle_bg = "#8f3f71"

[[block]]
block = "cpu"
interval = 1
[block.theme_overrides]
idle_bg = "#427b58"

[[block]]
block = "net"
format = " $icon  $ssid ^icon_net_down $speed_down.eng(prefix:K) ^icon_net_up $speed_up.eng(prefix:K) "
[block.theme_overrides]
idle_bg = "#689d6a"

[[block]]
block = "sound"
show_volume_when_muted = true
headphones_indicator = true
[block.theme_overrides]
idle_bg = "#d65d0e"

[[block]]
block = "battery"
# full_format = " $icon  $percentage "
# if_command = "test -e /sys/class/power_supply/BAT0"

[[block]]
block = "time"
interval = 1
[block.format]
full = " $icon $timestamp.datetime(f:'%a, %d %B %Y %T') "
[block.theme_overrides]
idle_bg = "#b16286"
