return {
    "theprimeagen/harpoon",

    config = function()
        local mark = require("harpoon.mark")
        local ui = require("harpoon.ui")

        vim.keymap.set("n", "<leader>a", mark.add_file)
        vim.keymap.set("n", "<leader>e", ui.toggle_quick_menu)

        vim.keymap.set("n", "<C-l>", function()
            ui.nav_next()
            vim.cmd("normal! zz")
        end)
        vim.keymap.set("n", "<C-h>", function()
            ui.nav_prev()
            vim.cmd("normal! zz")
        end)

        vim.keymap.set("n", "<A-1>", function()
            ui.nav_file(1)
            vim.cmd("normal! zz")
        end)
        vim.keymap.set("n", "<A-2>", function()
            ui.nav_file(2)
            vim.cmd("normal! zz")
        end)
        vim.keymap.set("n", "<A-3>", function()
            ui.nav_file(3)
            vim.cmd("normal! zz")
        end)
        vim.keymap.set("n", "<A-4>", function()
            ui.nav_file(4)
            vim.cmd("normal! zz")
        end)
        vim.keymap.set("n", "<A-5>", function()
            ui.nav_file(5)
            vim.cmd("normal! zz")
        end)
        vim.keymap.set("n", "<A-6>", function()
            ui.nav_file(6)
            vim.cmd("normal! zz")
        end)
        vim.keymap.set("n", "<A-7>", function()
            ui.nav_file(7)
            vim.cmd("normal! zz")
        end)
        vim.keymap.set("n", "<A-8>", function()
            ui.nav_file(8)
            vim.cmd("normal! zz")
        end)
        vim.keymap.set("n", "<A-9>", function()
            ui.nav_file(9)
            vim.cmd("normal! zz")
        end)
        vim.keymap.set("n", "<A-0>", function()
            ui.nav_file(0)
            vim.cmd("normal! zz")
        end)
    end,
}
